# -*- coding: utf-8 -*-
"""Day 2 Assigment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dVpY8yxZQrtn1DIf9XdV0N0ZtWYm87T5
"""

#Day 2 Assignment
import random
print("The Total Participants")
n=int(input())
names = [item for item in input("Enter the Names : ").split()] 
print("The winner of the Lottery is "+random.choice(names))

